/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ifpb.edu.br.sixpex.cliente;

import br.edu.ifpb.emailsharedpod.Email;
import br.edu.ifpb.emailsharedpod.Fachada;
import br.edu.ifpb.emailsharedpod.Pessoa;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Elisiany
 */
public class SisPexJFrame extends javax.swing.JFrame {

    private Fachada emailFachada;

    /**
     * Creates new form SixPexJFrame
     */
    public SisPexJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        inicializaFachada();
        preencheJListComEmails();
    }

    private void inicializaFachada() {
        emailFachada = SisPexLocator.lookup();
    }

    private void preencheJListComEmails() {
        try {
            List<Pessoa> pessoas = emailFachada.listaPessoas();
            DefaultListModel listModel = new DefaultListModel();
            listModel.clear();
            for (int i = 0; i < pessoas.size(); i++) {
                listModel.add(i, pessoas.get(i));
            }
            jListEmails.setModel(listModel);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmails = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        botaoEnviarEmails = new javax.swing.JButton();
        botaoCancelarEmails = new javax.swing.JButton();
        botaoRecarregaEmails = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoMensagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListEmails);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SixPex - Mala Direta");

        botaoEnviarEmails.setText("Enviar Email");
        botaoEnviarEmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarEmailsActionPerformed(evt);
            }
        });

        botaoCancelarEmails.setText("Cancelar");
        botaoCancelarEmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarEmailsActionPerformed(evt);
            }
        });

        botaoRecarregaEmails.setText("Recarregar Emails");
        botaoRecarregaEmails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRecarregaEmailsActionPerformed(evt);
            }
        });

        campoMensagem.setColumns(20);
        campoMensagem.setRows(5);
        campoMensagem.setToolTipText("Texto da Mensagem");
        jScrollPane2.setViewportView(campoMensagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(botaoRecarregaEmails))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(botaoCancelarEmails)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                            .addComponent(botaoEnviarEmails))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoRecarregaEmails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarEmails)
                    .addComponent(botaoEnviarEmails))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarEmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarEmailsActionPerformed

        List<Pessoa> pessoasSelecionadas = new ArrayList<>();
        DefaultListModel listModel = (DefaultListModel) jListEmails.getModel();

        int[] indicesSelecionados = jListEmails.getSelectedIndices();

        for (int index : indicesSelecionados) {
            pessoasSelecionadas.add((Pessoa) listModel.getElementAt(index));
        }

        if (pessoasSelecionadas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum Email Selecionado", "SisPex", JOptionPane.WARNING_MESSAGE);
        } else if (campoMensagem.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o texto da mensagem", "SisPex", JOptionPane.WARNING_MESSAGE);
        } else {
            try {

                Email email = new Email();
                email.setAssunto("Alerta elis");
                email.setMensagem(campoMensagem.getText());
                email.setDestinatarios(pessoasSelecionadas);

                String resposta = emailFachada.enviaEmail(email);
                
                JOptionPane.showMessageDialog(null, resposta, "SisPex", JOptionPane.INFORMATION_MESSAGE);
            } catch (RemoteException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "SisPex", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botaoEnviarEmailsActionPerformed

    private void botaoRecarregaEmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRecarregaEmailsActionPerformed
        preencheJListComEmails();
    }//GEN-LAST:event_botaoRecarregaEmailsActionPerformed

    private void botaoCancelarEmailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarEmailsActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoCancelarEmailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisPexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisPexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisPexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisPexJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisPexJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelarEmails;
    private javax.swing.JButton botaoEnviarEmails;
    private javax.swing.JButton botaoRecarregaEmails;
    private javax.swing.JTextArea campoMensagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListEmails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
